steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/user-service:latest', '.']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['container', 'images', 'add-tag', 'gcr.io/${PROJECT_ID}/user-service:latest', 'gcr.io/${PROJECT_ID}/user-service:latest-1']
- name: "gcr.io/cloud-builders/docker"
  args: ["push", 'gcr.io/${PROJECT_ID}/user-service:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=core-services'
options:
  logging: CLOUD_LOGGING_ONLY
