# $ kubectl apply -f deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: user-service-account
      containers:
      - name: user-service
        image: gcr.io/phading-dev/user-service:current
        ports:
        - containerPort: 80
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: user-service-monitoring
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
  - port: 80
    path: /metrics
    interval: 30s
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: user-serivce-neg-health-check
spec:
  healthCheck:
    port: 80
    type: HTTP
    requestPath: /healthz
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "user-serivce-neg-health-check"}'
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
