- message:
    name: AccountData
    fields:
      - name: naturalName
        type: string
        index: 1
      - name: contactEmail
        type: string
        index: 2
      - name: avatarSmallFilename
        type: string
        index: 3
      - name: avatarLargeFilename
        type: string
        index: 4
- spannerDatabase:
    name: UserDatabase
    tables:
      - name: User
        columns:
          - name: userId
            type: string
          - name: username
            type: string
          - name: passwordHashV1
            type: string
          - name: recoveryEmail
            type: string
          - name: createdTimestamp
            type: timestamp
            allowCommitTimestamp: true
        primaryKeys:
          - userId
        indexes:
          - name: UniqueUsername
            columns:
              - username
            unique: true
      - name: Account
        columns:
          - name: userId
            type: string
          - name: accountId
            type: string
          - name: accountType
            type: AccountType
            import: "@phading/user_service_interface/account_type"
          - name: data
            type: AccountData
          - name: description
            type: string
          - name: createdTimestamp
            type: timestamp
          - name: lastAccessedTimestamp
            type: timestamp
        primaryKeys:
          - accountId
        indexes:
          - name: ByUserAndLastAccessTimestamp
            columns:
              - userId
              - name: lastAccessedTimestamp
                desc: true
          - name: ByTypeAndCreatedTimestamp
            columns:
              - accountType
              - name: createdTimestamp
                desc: true
      - name: VideoPlayerSettings
        columns:
          - name: accountId
            type: string
          - name: settings
            type: VideoPlayerSettings
            import: "@phading/user_service_interface/web/self/video_player_settings"
        primaryKeys:
          - accountId
    inserts:
      - name: InsertNewUser
        table: User
        setColumns:
          - userId
          - username
          - passwordHashV1
          - recoveryEmail
          - createdTimestamp
      - name: InsertNewAccount
        table: Account
        setColumns:
          - userId
          - accountId
          - accountType
          - data
          - description
          - createdTimestamp
          - lastAccessedTimestamp
      - name: InsertNewVideoPlayerSettings
        table: VideoPlayerSettings
        setColumns:
          - accountId
          - settings
    updates:
      - name: UpdatePassword
        table: User
        where:
          op: =
          leftColumn: userId
        setColumns:
          - passwordHashV1
      - name: UpdateRecoveryEmail
        table: User
        where:
          op: =
          leftColumn: userId
        setColumns:
          - recoveryEmail
      - name: UpdateLastAccessedTimestmap
        table: Account
        where:
          op: =
          leftColumn: accountId
        setColumns:
          - lastAccessedTimestamp
      - name: UpdateAccountData
        table: Account
        where:
          op: =
          leftColumn: accountId
        setColumns:
          - data
      - name: UpdateAccountDescription
        table: Account
        where:
          op: =
          leftColumn: accountId
        setColumns:
          - description
      - name: UpdateVideoPlayerSettings
        table: VideoPlayerSettings
        where:
          op: =
          leftColumn: accountId
        setColumns:
          - settings
    deletes:
      - name: DeleteUser
        table: User
        where:
          op: =
          leftColumn: userId
      - name: DeleteAccount
        table: Account
        where:
          op: =
          leftColumn: accountId
      - name: DeleteVideoPlaySettings
        table: VideoPlayerSettings
        where:
          op: =
          leftColumn: accountId
    selects:
      - name: GetUserById
        table: User
        where:
          op: =
          leftColumn: userId
        getColumns:
          - username
          - passwordHashV1
          - recoveryEmail
      - name: GetUserByUsername
        table: User
        where:
          op: =
          leftColumn: username
        getColumns:
          - userId
          - passwordHashV1
      - name: GetLastAccessedAccount
        table: Account
        where:
          op: =
          leftColumn: userId
        orderBy:
          - column: lastAccessedTimestamp
            desc: true
        withLimit: true
        getColumns:
          - accountId
          - accountType
      - name: GetAccountById
        table: Account
        where:
          op: =
          leftColumn: accountId
        getColumns:
          - userId
          - accountType
          - data
      - name: GetAccountWithDescriptionById
        table: Account
        where:
          op: =
          leftColumn: accountId
        getColumns:
          - userId
          - accountType
          - data
          - description
      - name: ListAccounts
        table: Account
        where:
          op: =
          leftColumn: userId
        orderBy:
          - column: lastAccessedTimestamp
            desc: true
        getColumns:
          - accountId
          - accountType
          - data
      - name: ListAccountsByType
        table: Account
        where:
          op: AND
          exps:
            - op: <
              leftColumn: createdTimestamp
            - op: =
              leftColumn: accountType
        orderBy:
          - column: createdTimestamp
            desc: true
        withLimit: true
        getColumns:
          - accountId
          - createdTimestamp
      - name: GetAccountAndUser
        table:
          name: User
          as: u
        join:
          - type: INNER
            table:
              name: Account
              as: a
            on:
              op: =
              leftColumn:
                name: userId
                table: u
              rightColumn: userId
        where:
          op: AND
          exps:
            - op: =
              leftColumn:
                name: userId
                table: u
            - op: =
              leftColumn:
                name: accountId
                table: a
        getColumns:
          - name: username
            table: u
          - name: recoveryEmail
            table: u
          - name: data
            table: a
          - name: description
            table: a
      - name: GetVideoPlayerSettings
        table: VideoPlayerSettings
        where:
          op: =
          leftColumn: accountId
        getColumns:
          - settings
      - name: CheckPresenceOfVideoPlayerSettings
        table: VideoPlayerSettings
        where:
          op: =
          leftColumn: accountId
        getColumns:
          - accountId
    outputDdl: ./db/ddl
    outputSql: ./db/sql
