- kind: Message
  name: User
  fields:
    - name: userId
      type: string
      index: 1
    - name: username
      type: string
      index: 2
    - name: passwordHashV1
      type: string
      index: 3
    - name: recoveryEmail
      type: string
      index: 4
    - name: totalAccounts
      type: number
      index: 5
    - name: createdTimeMs
      type: number
      index: 6
- kind: Message
  name: BillingAccountStateInfo
  fields:
    - name: version
      type: number
      index: 1
    - name: state
      type: BillingAccountState
      import: "@phading/user_service_interface/node/billing_account_state"
      index: 2
- kind: Message
  name: Account
  fields:
    - name: userId
      type: string
      index: 1
    - name: accountId
      type: string
      index: 2
    - name: accountType
      type: AccountType
      import: "@phading/user_service_interface/account_type"
      index: 3
    - name: naturalName
      type: string
      index: 4
    - name: contactEmail
      type: string
      index: 5
    - name: avatarSmallFilename
      type: string
      index: 6
    - name: avatarLargeFilename
      type: string
      index: 7
    - name: lastAccessedTimeMs
      type: number
      index: 8
    - name: createdTimeMs
      type: number
      index: 9
    - name: billingAccountStateInfo
      type: BillingAccountStateInfo
      index: 10
    - name: capabilitiesVersion
      type: number
      index: 11
- kind: Message
  name: AccountMore
  fields:
    - name: accountId
      type: string
      index: 1
    - name: description
      type: string
      index: 2
- kind: SpannerDatabase
  name: UserDatabase
  tables:
    - kind: MessageTable
      name: User
      storedInColumn: data
      columns:
        - userId
        - username
      primaryKeys:
        - userId
      indexes:
        - name: UniqueUsername
          columns:
            - username
          unique: true
      insertStatementName: InsertUser
      deleteStatementName: DeleteUser
      getStatementName: GetUser
      updateStatementName: UpdateUser
    - kind: MessageTable
      name: Account
      storedInColumn: data
      columns:
        - accountId
        - userId
        - accountType
        - lastAccessedTimeMs
        - createdTimeMs
      primaryKeys:
        - accountId
      indexes:
        - name: ByUserAndLastAccessTimeMs
          columns:
            - userId
            - name: lastAccessedTimeMs
              desc: true
        - name: ByTypeAndCreatedTimeMs
          columns:
            - accountType
            - name: createdTimeMs
              desc: true
      insertStatementName: InsertAccount
      deleteStatementName: DeleteAccount
      getStatementName: GetAccount
      updateStatementName: UpdateAccount
    - kind: MessageTable
      name: AccountMore
      storedInColumn: data
      columns:
        - accountId
      primaryKeys:
        - accountId
      insertStatementName: InsertAccountMore
      deleteStatementName: DeleteAccountMore
      updateStatementName: UpdateAccountMore
    - kind: Table
      name: VideoPlayerSettings
      columns:
        - name: accountId
          type: string
        - name: settings
          type: VideoPlayerSettings
          import: "@phading/user_service_interface/web/self/video_player_settings"
      primaryKeys:
        - accountId
    - kind: Table
      name: AccountCapabilitiesUpdatingTask
      columns:
        - name: accountId
          type: string
        - name: capabilitiesVersion
          type: float64
        - name: executionTimeMs
          type: timestamp
        - name: createdTimeMs
          type: timestamp
      primaryKeys:
        - accountId
        - capabilitiesVersion
      indexes:
        - name: AccountCapabilitiesUpdatingTaskByExecutionTimeMs
          columns:
            - executionTimeMs
  inserts:
    - name: InsertVideoPlayerSettings
      table: VideoPlayerSettings
      setColumns:
        - accountId
        - settings
    - name: InsertAccountCapabilitiesUpdatingTask
      table: AccountCapabilitiesUpdatingTask
      setColumns:
        - accountId
        - capabilitiesVersion
        - executionTimeMs
        - createdTimeMs
  deletes:
    - name: DeleteVideoPlayerSettings
      table: VideoPlayerSettings
      where:
        op: =
        leftColumn: accountId
    - name: DeleteAccountCapabilitiesUpdatingTask
      table: AccountCapabilitiesUpdatingTask
      where:
        op: AND
        exps:
          - op: =
            leftColumn: accountId
          - op: =
            leftColumn: capabilitiesVersion
  updates:
    - name: UpdateVideoPlayerSettings
      table: VideoPlayerSettings
      where:
        op: =
        leftColumn: accountId
      setColumns:
        - settings
    - name: UpdateAccountCapabilitiesUpdatingTask
      table: AccountCapabilitiesUpdatingTask
      where:
        op: AND
        exps:
          - op: =
            leftColumn: accountId
          - op: =
            leftColumn: capabilitiesVersion
      setColumns:
        - executionTimeMs
  selects:
    - name: GetUserByUsername
      table: User
      where:
        op: =
        leftColumn: username
      getColumns:
        - data
    - name: ListLastAccessedAccounts
      table: Account
      where:
        op: =
        leftColumn: userId
      orderBy:
        - column: lastAccessedTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
    - name: GetAccountAndMoreById
      table:
        name: Account
        as: a
      join:
        - type: INNER
          table:
            name: AccountMore
            as: am
          on:
            op: =
            leftColumn:
              name: accountId
              table: a
            rightColumn: accountId
      where:
        op: =
        leftColumn: accountId
      getColumns:
        - name: data
          table: a
        - name: data
          table: am
    - name: GetUserAndAccountAndMore
      table:
        name: User
        as: u
      join:
        - type: INNER
          table:
            name: Account
            as: a
          on:
            op: =
            leftColumn:
              name: userId
              table: u
            rightColumn: userId
        - type: INNER
          table:
            name: AccountMore
            as: am
          on:
            op: =
            leftColumn:
              name: accountId
              table: a
            rightColumn: accountId
      where:
        op: AND
        exps:
          - op: =
            leftColumn:
              name: userId
              table: u
          - op: =
            leftColumn:
              name: accountId
              table: a
      getColumns:
        - name: data
          table: u
        - name: data
          table: a
        - name: data
          table: am
    - name: GetVideoPlayerSettings
      table: VideoPlayerSettings
      where:
        op: =
        leftColumn: accountId
      getColumns:
        - settings
    - name: CheckPresenceOfVideoPlayerSettings
      table: VideoPlayerSettings
      where:
        op: =
        leftColumn: accountId
      getColumns:
        - accountId
    - name: ListAccountCapabilitiesUpdatingTasks
      table: AccountCapabilitiesUpdatingTask
      where:
        op: <=
        leftColumn: executionTimeMs
      orderBy:
        - executionTimeMs
      getColumns:
        - accountId
        - capabilitiesVersion
        - executionTimeMs
  outputDdl: ./db/ddl
  outputSql: ./db/sql
